### ISSUE TITLE
Feature request: Add support for anime tv folders: HTTP Anidb Metadata Agent (HAMA)

### ISSUE THREAD

**Issue by shottothedome** [bstascavage/plexReport#20]
The default tvdb metadata agent has very poor support for anime. My anime section uses the zeroqi HAMA agent: https://github.com/ZeroQI/Hama.bundle - currently not compatible with plexReport's script.

When running the script plexReport exits with this:

plexReport.rb:126:in `getNewTVEpisodes': undefined method`[]' for nil:NilClass (NoMethodError)
        from plexReport.rb:215:in `main'
        from plexReport.rb:232:in`<main>'

**Comment by bstascavage** [comment]
It does.

Is this still an open ticket?

**Comment by shottothedome** [comment]
I've just gotten around this by making sure everything is pulled from thetvdb when possible (by manually changing teh matching). Anything being pulled from anidb.net does not show up.

**Comment by jedimstr** [comment]
Any chance this ticket could be looked at again?  Many Anime series and movies need the Hama agent to be managed correctly in Plex and switching to thetvdb.org agent would screw much of the Anime portion of my collection.  This is the one part of PlexReport that bugs me, missing a large portion of my library in the update emails I send out.

**Comment by ZeroQI** [comment]
HAMA maintainer here... 
If any info is needed i can provide it. I tried to look at this source but i am afraid i don't understand it...
