### ISSUE TITLE
PlexReport broken after upgrade to 15.04

### ISSUE THREAD

**Issue by broyuken** [bstascavage/plexReport#57]
I upgraded to 15.04 and now whenever I try to run the report, I get the following error:

user@hostname:/etc/plexReport$ /usr/local/sbin/plexreport -t
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- i18n (LoadError)
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/sbin/plexreport:11:in `<main>'

I have the gem installed, so I'm not sure what this error could mean.
user@hostname:/etc/plexReport$ gem list --local | grep i18n
i18n (0.7.0)

**Comment by broyuken** [comment]
I removed and re-installed plexReport, and all is well again.
