### ISSUE TITLE
Error sending gmail

### ISSUE THREAD

**Issue by elRadix** [bstascavage/plexReport#58]
I cant send a gmail anymore. How can this be fixed ?

```
root@DD-WRT:/opt/plexReport# /usr/local/sbin/plexreport -t 
/var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail/core_extensions/string.rb:26:in `=~': invalid byte sequence in US-ASCII (ArgumentError)
	from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail/core_extensions/string.rb:26:in `!~'
	from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail/core_extensions/string.rb:26:in `blank?'
	from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail/body.rb:36:in `initialize'
	from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:2012:in `new'
	from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:2012:in `process_body_raw'
	from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:1244:in `body'
	from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:2038:in `identify_and_set_transfer_encoding'
	from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:1792:in `ready_to_send!'
	from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:1810:in `encoded'
	from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail/check_delivery_params.rb:12:in `check_delivery_params'
	from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:98:in `deliver!'
	from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:252:in `deliver!'
	from /var/lib/plexReport/mailReport.rb:93:in `block in sendMail'
	from /var/lib/plexReport/mailReport.rb:84:in `each'
	from /var/lib/plexReport/mailReport.rb:84:in `sendMail'
	from /usr/local/sbin/plexreport:381:in `main'
	from /usr/local/sbin/plexreport:385:in `<main>'

```

**Comment by bstascavage** [comment]
What does your config look like?

**Comment by bstascavage** [comment]
Following up on this.

**Comment by elRadix** [comment]
this is the content of the config

---
email:
  title: TV and Movies
plex:
  server: 192.168.1.2
  api_key: xxxxxx
mail:
  address: smtp.gmail.com
  port: '587'
  username: xxxx@gmail.com
  password: xxxxx
  from: Plex Updates
  subject: Weekly Updates of Series and Movies

**Comment by elRadix** [comment]
just tried again without -t command
---
root@xxxx:/etc/plexReport# /usr/local/sbin/plexreport -d
/var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail/check_delivery_params.rb:9:in `check_delivery_params': An SMTP To address is required to send a message. Set the message smtp_envelope_to, to, cc, or bcc address. (ArgumentError)
	from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:98:in `deliver!'
	from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:252:in `deliver!'
	from /var/lib/plexReport/mailReport.rb:93:in `block in sendMail'
	from /var/lib/plexReport/mailReport.rb:84:in `each'
	from /var/lib/plexReport/mailReport.rb:84:in `sendMail'
	from /usr/local/sbin/plexreport:381:in `main'
	from /usr/local/sbin/plexreport:385:in `<main>'

**Comment by bstascavage** [comment]
Ok, so when you run it with -t it works, but doesn't when you don't?

Can you give me the output of:

https://plex.tv/pms/friends/all

?

**Comment by elRadix** [comment]
here is the output
```javascript
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<MediaContainer friendlyName="myPlex" identifier="com.plexapp.plugins.myplex" machineIdentifier="xxxxxxxx" totalSize="5" size="5">
<script/>
<User id="938844" title="xxxx" username="xxx" email="xx@xxxx.be" recommendationsPlaylistId="0da07cd1cbad5476" thumb="https://secure.gravatar.com/avatar/xxxx?d=https%3A%2F%2Fplex.tv%2Favatars%2F8C8165%2F48%2F1">
<Server id="199937" serverId="xxx" machineIdentifier="xxxx" name="HvacLine" lastSeenAt="1437791062" numLibraries="5" owned="0"/>
<Server id="2161498" serverId="1158052" machineIdentifier="xxx" name="xxxx" lastSeenAt="1439547523" numLibraries="3" owned="1"/>
</User>
<User id="5832720" title="Kids" username="" email="" recommendationsPlaylistId="c0b61b8dba27fcc8" thumb="https://plex.tv/avatars/EB9F9F/4b/1"></User>
<User id="5832724" title="Kids" username="" email="" recommendationsPlaylistId="89dabb6608ef79bd" thumb="https://plex.tv/avatars/8C8165/4b/1"></User>
<User id="3209442" title="merwone" username="merwone" email="xxxxx@gmail.com" recommendationsPlaylistId="fd13de43c7b86207" thumb="https://secure.gravatar.com/avatar/xxxxx?d=https%3A%2F%2Fplex.tv%2Favatars%2F7EB0D5%2F4d%2F1">
<Server id="967023" serverId="2442420" machineIdentifier="xxxx" name="merwone" lastSeenAt="1435750225" numLibraries="2" owned="0"/>
<Server id="2161497" serverId="1158052" machineIdentifier="xxxx" name="FloRaMac" lastSeenAt="1439547523" numLibraries="4" owned="1"/>
</User>
<User id="1089415" title="xxxx" username="xxx" email="xxxx@gmail.com" recommendationsPlaylistId="298fa5847d1b3d1b" thumb="https://secure.gravatar.com/avatar/xxxx?d=https%3A%2F%2Fplex.tv%2Favatars%2FF18052%2F53%2F1">
<Server id="1351417" serverId="1158052" machineIdentifier="xxxxx" name="FloRaMac" lastSeenAt="1439547523" numLibraries="8" owned="1"/>
</User>
</MediaContainer>

```

**Comment by bstascavage** [comment]
Ah, thats it!  There are blank emails there.

Let me update the code to check for that (I didn't even know that was a possibility)

**Comment by bstascavage** [comment]
Ok, I updated the code.  Update your end and give it a shot.

**Comment by elRadix** [comment]
perfect, just updated and now it works, thank you for the fix!!
