### ISSUE TITLE
error sending email

### ISSUE THREAD

**Issue by EnderBlue** [bstascavage/plexReport#69]
I get the at the bottom of this post.  I have added some debug logging and confirmed that the recipient email address is valid and the created email itself is also valid.  I think it must be something with differences in character sets, because it keeps crashing when trying to evaluate the email "string".

ERROR:
mail-2.6.3/lib/mail/core_extensions/string.rb:26:in `=~': invalid byte sequence in US-ASCII (ArgumentError)
mail-2.6.3/lib/mail/body.rb:36:in`initialize'

**Comment by kmlucy** [comment]
I am also getting this error.

**Comment by kmlucy** [comment]
I fixed it with:
```
export LC_ALL=C.UTF-8
export LANG=en_US.UTF-8 
export LANGUAGE=en_US.UTF-8
```

**Comment by evanrich** [comment]
@kmlucy  your solution doesn't work on  freebsd..  everything else works up to generating a test report.    In freebsd, I ran "setenv LC_ALL C.UTF-8", etc...no joy

```
/usr/local/lib/ruby/gems/2.2/gems/mail-2.6.3/lib/mail/core_extensions/string.rb:26:in `=~': invalid byte sequence in US-ASCII (ArgumentError)
        from /usr/local/lib/ruby/gems/2.2/gems/mail-2.6.3/lib/mail/core_extensions/string.rb:26:in `!~'
        from /usr/local/lib/ruby/gems/2.2/gems/mail-2.6.3/lib/mail/core_extensions/string.rb:26:in `blank?'
        from /usr/local/lib/ruby/gems/2.2/gems/mail-2.6.3/lib/mail/body.rb:36:in `initialize'
        from /usr/local/lib/ruby/gems/2.2/gems/mail-2.6.3/lib/mail/message.rb:2012:in `new'
        from /usr/local/lib/ruby/gems/2.2/gems/mail-2.6.3/lib/mail/message.rb:2012:in `process_body_raw'
        from /usr/local/lib/ruby/gems/2.2/gems/mail-2.6.3/lib/mail/message.rb:1244:in `body'
        from /usr/local/lib/ruby/gems/2.2/gems/mail-2.6.3/lib/mail/message.rb:2038:in `identify_and_set_transfer_encoding'
        from /usr/local/lib/ruby/gems/2.2/gems/mail-2.6.3/lib/mail/message.rb:1792:in `ready_to_send!'
        from /usr/local/lib/ruby/gems/2.2/gems/mail-2.6.3/lib/mail/message.rb:1810:in `encoded'
        from /usr/local/lib/ruby/gems/2.2/gems/mail-2.6.3/lib/mail/check_delivery_params.rb:12:in `check_delivery_params'
        from /usr/local/lib/ruby/gems/2.2/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:98:in `deliver!'
        from /usr/local/lib/ruby/gems/2.2/gems/mail-2.6.3/lib/mail/message.rb:252:in `deliver!'
        from /var/lib/plexReport/mailReport.rb:95:in `block in sendMail'
        from /var/lib/plexReport/mailReport.rb:86:in `each'
        from /var/lib/plexReport/mailReport.rb:86:in `sendMail'
        from /usr/local/sbin/plexreport:381:in `main'
        from /usr/local/sbin/plexreport:385:in `<main>'
root@plexmediaserver_1:/usr/local/sbin # echo $LANGUAGE
en_US.UTF-8
root@plexmediaserver_1:/usr/local/sbin # echo LC_ALL
LC_ALL
root@plexmediaserver_1:/usr/local/sbin # echo $LC_ALL
C.UTF-8
root@plexmediaserver_1:/usr/local/sbin # echo $LC_ALL
C.UTF-8
root@plexmediaserver_1:/usr/local/sbin # echo $LANG
en_US.UTF-8
root@plexmediaserver_1:/usr/local/sbin # echo $LANGUAGE
en_US.UTF-8
```

**Comment by evanrich** [comment]
in freebsd, these had to be set:

```
setenv  RUBYOPT '-E utf-8'
setenv LC_ALL C.UTF-8
setenv LANG en_US.UTF-8
setenv LANGUAGE en_US.UTF-8
```
