### ISSUE TITLE
Unable to run a report

### ISSUE THREAD

**Issue by ChrisColotti** [bstascavage/plexReport#77]
I was just trying to get this working and the install was fine, the setup worked but if I run a test all I get is this:

ccolotti@PlexWatch:/opt/plexReport$ sudo plexreport -t
/usr/lib/ruby/1.9.1/net/protocol.rb:141:in `read_nonblock': end of file reached (EOFError)
	from /usr/lib/ruby/1.9.1/net/protocol.rb:141:in `rbuf_fill'
	from /usr/lib/ruby/1.9.1/net/protocol.rb:122:in `readuntil'
	from /usr/lib/ruby/1.9.1/net/protocol.rb:132:in `readline'
	from /usr/lib/ruby/1.9.1/net/smtp.rb:929:in `recv_response'
	from /usr/lib/ruby/1.9.1/net/smtp.rb:552:in `block in do_start'
	from /usr/lib/ruby/1.9.1/net/smtp.rb:939:in `critical'
	from /usr/lib/ruby/1.9.1/net/smtp.rb:552:in `do_start'
	from /usr/lib/ruby/1.9.1/net/smtp.rb:519:in `start'
	from /var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
	from /var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/message.rb:252:in `deliver!'
	from /var/lib/plexReport/mailReport.rb:95:in `block in sendMail'
	from /var/lib/plexReport/mailReport.rb:86:in `each'
	from /var/lib/plexReport/mailReport.rb:86:in `sendMail'
	from /usr/local/sbin/plexreport:381:in `main'
	from /usr/local/sbin/plexreport:385:in `<main>

**Comment by ChrisColotti** [comment]
ccolotti@PlexWatch:/opt/plexReport$ ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [i686-linux]

**Comment by ChrisColotti** [comment]
I get the same error as above just running "plexreport -v" seems like something is wrong with ruby maybe?
