### ISSUE TITLE
Conflict Error - Ruby / json

### ISSUE THREAD

**Issue by Monstar316** [bstascavage/plexReport#80]
Hi,

I received the below output when the scheduled job in cron tried to run plexReport:

/usr/lib/ruby/2.3.0/rubygems/specification.rb:2286:in `raise_if_conflicts': Unable to activate httparty-0.13.1, because json-2.0.1 conflicts with json (~> 1.8) (Gem::ConflictError)
        from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1407:in `activate'
        from /usr/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
        from /usr/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /var/lib/plexReport/plex.rb:4:in `<top (required)>'
        from /usr/local/sbin/plexreport:14:in `require_relative'
        from /usr/local/sbin/plexreport:14:in `<main>'

I tried running it manually and got the same output.

Do you know how to resolve this?

**Comment by Monstar316** [comment]
Resolved after numerous attempts to remove all files relating to plexReport and re-installing. Working after 4th-5th attempt.
